### PR TITLE
Simplify the build system

### PR DESCRIPTION
**Pull request by fingolfin**
... and fix several issues by doing so. In particular, we don't need to
worry about `configure` working right (which it often didn't, namely if
the CPPFLAGS/CFLAGS/CXXFLAGS/LDFLAGS didn't align exactly with the
corresponding Python settings for include_dirs, library_dirs, etc.)

This fixes all .so issues for me on macOS.

### CODE REVIEW

**Comment by w-bruns** [comment]
Unclear to me where the problem on Travis is.

**Comment by fingolfin** [comment]
I forgot to update the .travis.yml. Will do once I arrived home

**Comment by fingolfin** [comment]
@w-bruns now Travis passes.

BTW, I test it with this command:
```
rm -rf build/ && NORMALIZ_LOCAL_DIR=PATH/TO/NORMALIZ/local python setup.py install && python -c 'import PyNormaliz'
```

**Comment by fingolfin** [comment]
If this also works for @w-bruns is the best kind of fix: removing 1061 lines, and modifying 3, to get stuff working ;-). That said, there may be further cases I have not yet considered where things break; if so, just let me know and I'll try to fix them as well.

**Comment by w-bruns** [comment]
I am merging this PR now. Will be tested outside of Travis.

**Pull request merged**
