### PR TITLE
add slash to configure invocation

### PR DESCRIPTION
**Pull request by videlec**
Fix https://github.com/Normaliz/PyNormaliz/issues/56

### CODE REVIEW

**Comment by sebasguts** [comment]
@videlec Travis does not seem to like it. I will have a look.

**Comment by videlec** [comment]
Travis does not like your travis script. I mentioned that on zulip.

**Comment by videlec** [comment]
The travis problem is visible on master. It is independent of this PR.

**Comment by orlitzky** [comment]
At first this doesn't seem like it could possibly be the root cause of the problem, but after much head-scratching, I now believe that it's the correct fix.

When you run `sh configure` with a shell that doesn't support the `LINENO` variable, the configure script will try to re-exec itself with a shell (usually `/bin/bash`) that does support `LINENO`. However, there's a bug in that re-exec routine whenever the name of the configure script (simply `configure`, in this case) doesn't contain a slash. Instead of re-exec'ing the script you want, you can get a random one from your `$PATH`.

Maybe that will get fixed in autoconf, but in the meantime, it's certainly easiest and perfectly correct to put the slash in `./configure`.

**Comment by videlec** [comment]
@sebasguts Is there any problem with the PR?

**Comment by sebasguts** [comment]
@videlec no, absolutely not. I am currently investigating the travis failure, and will merge it afterwards

**Comment by mkoeppe** [comment]
Can we get a new release with this fix please?

**Comment by sebasguts** [comment]
Done :)

**Comment by mkoeppe** [comment]
not available on pypi yet

**Comment by sebasguts** [comment]
Should be uploaded now. Apparently, there was a typo in the Readme, and PyPI now checks if it can parse it.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
