### PR TITLE
configure.ac: don't use Cone<mpq_class>

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by w-bruns** [comment]
I am confused. Which version of Normaliz does it use? I try merging. Perhaps it is o.k.if it is on the Normaliz side.

**Comment by fingolfin** [comment]
I don't under what the confusion is about..? And I don't under the question about "what version of normaliz" either? Are you asking which version of normaliz is used by the pynormaliz ci tests, or what?

**Comment by w-bruns** [comment]
The confusion arose since the Travis builds of this PR failed after the builds in Normaliz/PyNormaliz had been successful. But after merging the builds were o.k. again. Of course since the branch master of Normaliz/Normaliz had been updated by moving the critical function into cone.h. 

Indeed, the question is what repository or branch is used when Travis builds PyNormaliz. My impression is that Normaliz(Normaliz/master is used if the builds come from Mormaliz/PyNormaliz.

**Comment by fingolfin** [comment]
No need to guess, you can look at `.travis.yml` to find out; it calls `./.travis-install-normaliz.sh`, which then does this, among other things:
```
# install normaliz
git clone --depth=1 https://github.com/Normaliz/Normaliz
cd Normaliz
```

So it indeed always uses the Normaliz master branch.

**Comment by w-bruns** [comment]
Hmm, how could the Travis builds of the PR then fail? I think this PR was launched after we had updated the master branch.

**Comment by fingolfin** [comment]
Nope, this PR was created 9 hours ago and updated 8 hours ago; your changes were made a bit later. :-)

**Pull request merged**
