### PR TITLE
Add pretty print polynomial function for Hilbert series, fix formatting

### PR DESCRIPTION
**Pull request by JustinShenk**

### CODE REVIEW

**Comment by sebasguts** [comment]
Could you provide two commits for the formatting and the print function?
You can add only part of changes in files by using `git add -p <filename>`.

**Comment by JustinShenk** [comment]
Yes, I will fix that, thanks.

**Comment by sebasguts** [comment]
This code does not work.

**Comment by sebasguts** [comment]
I reverted the merge for now. I will fix the issues, then merge it again.

**Comment by sebasguts** [comment]
Fixed the issues.

**Comment by JustinShenk** [comment]
Thank you!

**Pull request merged**
