### PR TITLE
Added dynamic methods to python Cone class

### PR DESCRIPTION
**Pull request by jplab**
Comments welcome!

### CODE REVIEW

**Comment by videlec** [comment]
This is very bad with respect to tab-completion...

**Comment by videlec** [comment]
Your `__getattr__` will be called once for each couple `(instance, method)` whereas it should rather be called once for each `method`. More precisely, with the current version there would be two resolution via `__getattr__`
```
>>> cone1 = Cone(...)
>>> cone2 = Cone()
>>> cone1.Whatever()
>>> cone2.Whatever()
```

**Comment by sebasguts** [comment]
@videlec Would it be better if we created the method explicitly in the setup.py?

**Comment by jplab** [comment]
> This is very bad with respect to tab-completion...

Yes, agreed! There was no tab completion beforehand either...

**Comment by videlec** [comment]
@sebasguts At build time would be an option. Please do not put it inside `setup.py` but rather an external `autogen.py` or whatever name you find convenient. This `autogen.py` would be called from `setup.py` of course.

**Comment by jplab** [comment]
> Your `__getattr__` will be called once for each couple `(instance, method)` whereas it should rather be called once for each `method`. More precisely, with the current version there would be two resolution via `__getattr__`
> 
> ```
> >>> cone1 = Cone(...)
> >>> cone2 = Cone()
> >>> cone1.Whatever()
> >>> cone2.Whatever()
> ```

Hmm. Ok. is there a slick way to make create it only once per method without using metaclasses?

**Comment by sebasguts** [comment]
@videlec Yeah, makes sense. No need to pollute the `setup.py`

**Comment by fingolfin** [comment]
Hi folks, what's the status of this PR? Any plans to work more on it in either direction? I.e. either by generating code, or by somehow making the `__getattr__` idea better?

**Pull request closed without merging**
